### PR TITLE
[WIP] add feature to run predefined terminal commands from pad

### PR DESCRIPTION
**Pull request by luelista**
maybe to be used for bookstack export

### CODE REVIEW

**Comment by jlauinger** [comment]
Where is the definition of what commands may be executed?

**Comment by miterion** [comment]
Looks good to me

**Comment by max-weller** [comment]
> Where is the definition of what commands may be executed?

Das fehlt noch, bisher gibts nur nen Test-Command - https://github.com/d120/padman/pull/32/files#diff-f0153bcb86483c21f87649be7e0b5c46R149

**Comment by max-weller** [comment]
merged in 0d038a66117510ece04fd914b500f0efd4ab05ef

**Pull request closed without merging**
